# Generated by Django 3.0.2 on 2020-02-08 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('habits_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
            preserve_default=False,
        ),
    ]
