# Generated by Django 3.0.2 on 2020-02-08 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits_tracker', '0002_goal_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_title', models.CharField(max_length=40)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits_tracker.Goal')),
            ],
        ),
    ]
