# Generated by Django 3.0.2 on 2020-02-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits_tracker', '0004_habit_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='notes',
            field=models.TextField(default='', null=True),
        ),
    ]
