# Generated by Django 3.0.2 on 2020-01-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits_tracker', '0005_auto_20200126_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='person',
        ),
        migrations.AddField(
            model_name='goal',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
