# Generated by Django 3.0.2 on 2020-02-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits_tracker', '0006_auto_20200209_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_status',
            field=models.CharField(choices=[('To Start', 'TS'), ('In Progress', 'PR'), ('Achieved', 'AC')], default='To Start', max_length=20),
        ),
    ]
