# Generated by Django 3.0.2 on 2020-01-26 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits_tracker', '0006_auto_20200126_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='id',
        ),
        migrations.AddField(
            model_name='goal',
            name='person',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='habits_tracker.Person'),
            preserve_default=False,
        ),
    ]
