# Generated by Django 3.0.2 on 2020-01-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits_tracker', '0007_auto_20200126_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysCommitted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='goal',
            options={},
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_title', models.CharField(max_length=40)),
                ('habit_desc', models.CharField(max_length=200)),
                ('goal', models.ManyToManyField(to='habits_tracker.Person')),
            ],
        ),
    ]
