# Generated by Django 3.0.2 on 2020-02-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits_tracker', '0007_auto_20200209_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_status',
            field=models.CharField(choices=[('TS', 'To Start'), ('PR', 'In Progress'), ('AC', 'Achieved')], default='TS', max_length=20),
        ),
    ]
