# Generated by Django 3.0.2 on 2020-02-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits_tracker', '0008_auto_20200209_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_status',
            field=models.CharField(choices=[('To Start', 'To Start'), ('In Progress', 'In Progress'), ('Achieved', 'Achieved')], default='To Start', max_length=11),
        ),
    ]
