# Generated by Django 3.0.2 on 2020-01-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits_tracker', '0009_auto_20200126_2214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DaysCommitted',
        ),
        migrations.AddField(
            model_name='habit',
            name='commited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='preparations',
            field=models.TextField(blank=True),
        ),
    ]
