# Generated by Django 3.0.2 on 2020-01-27 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits_tracker', '0010_auto_20200127_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='habits_tracker.Person'),
        ),
    ]
