# Generated by Django 3.0.2 on 2020-01-27 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits_tracker', '0013_auto_20200127_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='practised_today',
            field=models.DateField(default=datetime.date(2020, 1, 27)),
            preserve_default=False,
        ),
    ]
