# Generated by Django 3.0.2 on 2020-01-27 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits_tracker', '0014_habit_practised_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='habit_title',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracked_date', models.DateField()),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits_tracker.Habit')),
            ],
        ),
    ]
