# Generated by Django 3.0.2 on 2020-01-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits_tracker', '0015_auto_20200127_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='tracked_date',
            field=models.DateField(unique=True),
        ),
    ]
