# Generated by Django 3.0.2 on 2020-01-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits_tracker', '0016_auto_20200127_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='mantra',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='notes',
            field=models.TextField(blank=True),

        ),
    ]
