# Generated by Django 3.0.2 on 2020-01-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits_tracker', '0017_auto_20200127_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='notes',
            field=models.TextField(),
        ),
    ]
