# Generated by Django 3.0.2 on 2020-02-04 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits_tracker', '0019_person_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='habits_tracker.Person'),
        ),
    ]
