# Generated by Django 3.0.2 on 2020-02-04 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('habits_tracker', '0022_auto_20200204_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.Profile'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
