# Generated by Django 3.0.2 on 2020-02-19 23:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TDLheading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('duedate', models.DateTimeField(default=datetime.datetime(2020, 2, 20, 18, 0))),
                ('heading', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='todolist.TDLheading')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='TodoListitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('notes', models.TextField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.Todolist')),
            ],
        ),
    ]
