# Generated by Django 3.0.2 on 2020-02-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdlheading',
            name='header',
            field=models.CharField(default='weekly', max_length=25),
            preserve_default=False,
        ),
    ]
