# Generated by Django 3.0.2 on 2020-02-19 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('todolist', '0002_tdlheading_header'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todolist',
            new_name='TDL',
        ),
    ]
