# Generated by Django 3.0.2 on 2020-02-20 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20200219_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdl',
            name='duedate',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 21, 18, 0)),
        ),
    ]
