# Generated by Django 3.0.2 on 2020-02-20 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20200220_1836'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoListitem',
            new_name='TDLitem',
        ),
    ]
