# Generated by Django 3.0.2 on 2020-02-21 22:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('todolist', '0006_auto_20200221_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='TDLhead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=25)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='TDLnotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TDLsubtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='tdlitem',
            name='node',
        ),
        migrations.RemoveField(
            model_name='tdlitem',
            name='notes',
        ),
        migrations.AddField(
            model_name='tdlitem',
            name='duedate',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 22, 18, 0)),
        ),
        migrations.AddField(
            model_name='tdlitem',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TDL',
        ),
        migrations.DeleteModel(
            name='TDLheading',
        ),
        migrations.AddField(
            model_name='tdlsubtitle',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.TDLitem'),
        ),
        migrations.AddField(
            model_name='tdlnotes',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.TDLitem'),
        ),
        migrations.AddField(
            model_name='tdlitem',
            name='tdlhead',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todolist.TDLhead'),
            preserve_default=False,
        ),
    ]
