# Generated by Django 3.0.2 on 2020-02-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_auto_20200221_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdlsubtitle',
            name='sub_status',
            field=models.BooleanField(default=False),
        ),
    ]
