# Generated by Django 3.0.2 on 2020-02-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0008_tdlsubtitle_sub_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdlhead',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
