# Generated by Django 3.0.2 on 2020-02-25 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0009_tdlhead_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdlitem',
            name='duedate',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 26, 18, 0)),
        ),
    ]
