# Generated by Django 3.0.2 on 2020-03-03 15:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('todolist', '0010_auto_20200225_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tdlitem',
            name='tdlhead',
        ),
        migrations.AddField(
            model_name='tdlitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tdlitem',
            name='header',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tdlitem',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tdlitem',
            name='duedate',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 4, 18, 0)),
        ),
        migrations.DeleteModel(
            name='TDLhead',
        ),
    ]
