# Generated by Django 3.0.2 on 2020-03-03 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('todolist', '0013_auto_20200303_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tditem',
            old_name='title',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='tdlist',
            old_name='header',
            new_name='title',
        ),
        migrations.AddField(
            model_name='tditem',
            name='tdlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
            preserve_default=False,
        ),
    ]
