# Generated by Django 3.0.2 on 2020-03-03 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0014_auto_20200303_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tditem',
            name='tdlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.TDlist'),
        ),
    ]
