# Generated by Django 3.0.2 on 2020-03-09 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0015_auto_20200303_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tditem',
            name='duedate',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 18, 0)),
        ),
    ]
