# Generated by Django 3.0.2 on 2020-03-10 14:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0016_auto_20200309_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tditem',
            options={'ordering': ['duedate']},
        ),
        migrations.AlterField(
            model_name='tditem',
            name='duedate',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 11, 18, 0, tzinfo=utc)),
        ),
    ]
